package net.meshnet.core.mesh.ble

import java.io.ByteArrayOutputStream

/**
 * Reassembles chunks generated by [PacketFragmenter].
 * Maintains state for an ongoing transfer.
 */
class ChunkReassembler {

    private var activeTransferId: Short? = null
    private var nextSeq: Int = 0
    private val buffer = ByteArrayOutputStream()

    /**
     * Processes an incoming chunk.
     * 
     * @return The complete assembled byte array if this chunk was the END chunk and
     *         reassembly was successful. null if more chunks are needed.
     * @throws ReassemblyException if chunks are out of order, transfer ID mismatches, etc.
     */
    @Throws(ReassemblyException::class)
    fun processChunk(chunk: ByteArray): ByteArray? {
        if (chunk.size < PacketFragmenter.HEADER_SIZE) {
            throw ReassemblyException("Chunk too small")
        }

        val header = PacketFragmenter.parseHeader(chunk)
        val payload = chunk.copyOfRange(PacketFragmenter.HEADER_SIZE, chunk.size)

        if (header.isStart) {
            // Reset state for a new transfer
            buffer.reset()
            activeTransferId = header.transferId
            nextSeq = 0
        } else {
            // Must have an active transfer
            if (activeTransferId == null) {
                throw ReassemblyException("Received non-START chunk without an active transfer")
            }
            if (activeTransferId != header.transferId) {
                throw ReassemblyException("Transfer ID mismatch: expected $activeTransferId, got ${header.transferId}")
            }
        }

        // Sequence check
        if (header.seq != nextSeq) {
            val expected = nextSeq
            reset() // Corrupted transfer, discard buffer
            throw ReassemblyException("Out of order chunk. Expected seq $expected, got ${header.seq}")
        }

        // Append data
        buffer.write(payload)
        nextSeq = (nextSeq + 1) % 256

        if (header.isEnd) {
            val completeData = buffer.toByteArray()
            reset() // Ready for next transfer
            return completeData
        }

        return null
    }

    /** Discards current buffer and resets state. */
    fun reset() {
        buffer.reset()
        activeTransferId = null
        nextSeq = 0
    }
}

class ReassemblyException(message: String) : Exception(message)
